"""
Lifecycle Hook Manager for the yt_transcriptor pipeline.

Parses `hooks.json` configuration, registers hook callbacks, and provides safe execution
mechanisms for pipeline lifecycle events (e.g., pre_pipeline, post_pipeline, on_log, on_progress, on_phase).
"""

import importlib
import json
import logging
import os
from typing import Dict, List, Callable, Any, Optional

logger = logging.getLogger(__name__)

DEFAULT_HOOKS_CONFIG: Dict[str, Any] = {
    "version": "1.0.0",
    "hooks": {
        "on_log": {
            "name": "on_log",
            "event": "pipeline_log",
            "description": "Triggered when a log message is generated by the pipeline",
            "handler": "gateway.pipeline_service:get_on_log_callback",
            "signature": "on_log(message: str) -> None"
        },
        "on_progress": {
            "name": "on_progress",
            "event": "pipeline_progress",
            "description": "Triggered when chapter progress updates",
            "handler": "gateway.pipeline_service:get_on_progress_callback",
            "signature": "on_progress(current: int, total: int, step: str = 'Processing...') -> None"
        },
        "on_phase": {
            "name": "on_phase",
            "event": "pipeline_phase_change",
            "description": "Triggered when pipeline transitions phase status",
            "handler": "gateway.pipeline_service:get_on_phase_callback",
            "signature": "on_phase(phase: str, status: str) -> None"
        },
        "pre_pipeline": {
            "name": "pre_pipeline",
            "event": "pre_pipeline_start",
            "description": "Lifecycle hook triggered before pipeline execution begins",
            "signature": "pre_pipeline(context: dict) -> None"
        },
        "post_pipeline": {
            "name": "post_pipeline",
            "event": "post_pipeline_finish",
            "description": "Lifecycle hook triggered after pipeline execution completes or fails",
            "signature": "post_pipeline(context: dict) -> None"
        }
    }
}


def load_hooks_config(config_path: str = "hooks.json") -> Dict[str, Any]:
    """Load hooks configuration from a JSON file, falling back to default configuration if missing or invalid.

    Args:
        config_path: Path to the hooks JSON configuration file.

    Returns:
        Dict[str, Any]: Parsed hook configuration dictionary.
    """
    if os.path.exists(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                if isinstance(data, dict) and "hooks" in data:
                    return data
        except Exception as err:
            logger.warning(f"Failed to load hooks config from {config_path}: {err}. Using defaults.")
    return DEFAULT_HOOKS_CONFIG


def resolve_handler_string(handler_str: str) -> Optional[Callable[..., Any]]:
    """Dynamically resolve a handler string of format 'module.path:function_name' or 'module.path.function_name'.

    Args:
        handler_str: String specifying module path and function name.

    Returns:
        Optional[Callable]: Resolved callable if successfully imported, None otherwise.
    """
    if not handler_str:
        return None
    try:
        if ":" in handler_str:
            mod_name, func_name = handler_str.split(":", 1)
        else:
            mod_name, func_name = handler_str.rsplit(".", 1)
        mod = importlib.import_module(mod_name)
        return getattr(mod, func_name, None)
    except Exception as err:
        logger.debug(f"Could not resolve handler '{handler_str}': {err}")
        return None


class HookManager:
    """Manager for lifecycle hooks and event handlers during pipeline execution."""

    def __init__(self, config_path: str = "hooks.json") -> None:
        """Initialize HookManager with configuration, empty handler registries, and auto-binding.

        Args:
            config_path: Path to hooks configuration JSON.
        """
        self.config: Dict[str, Any] = load_hooks_config(config_path)
        self.handlers: Dict[str, List[Callable[..., Any]]] = {
            "on_log": [],
            "on_progress": [],
            "on_phase": [],
            "pre_pipeline": [],
            "post_pipeline": []
        }
        self._auto_bind_configured_handlers()

    def _auto_bind_configured_handlers(self) -> None:
        """Inspect config for declared handler entrypoints and attempt dynamic auto-binding."""
        hooks_def = self.config.get("hooks", {})
        if not isinstance(hooks_def, dict):
            return
        for hook_name, hook_info in hooks_def.items():
            if isinstance(hook_info, dict) and "handler" in hook_info:
                handler_str = hook_info.get("handler")
                if handler_str and isinstance(handler_str, str):
                    fn = resolve_handler_string(handler_str)
                    if fn:
                        self.register(hook_name, fn)

    def register(self, hook_name: str, handler: Optional[Callable[..., Any]]) -> None:
        """Register a callback handler for a specific hook lifecycle event.

        Args:
            hook_name: Name of the hook event (e.g. 'on_log', 'pre_pipeline').
            handler: Callable to execute when the hook triggers.
        """
        if handler is None:
            return
        if hook_name not in self.handlers:
            self.handlers[hook_name] = []
        if handler not in self.handlers[hook_name]:
            self.handlers[hook_name].append(handler)

    def unregister(self, hook_name: str, handler: Callable[..., Any]) -> None:
        """Unregister a handler callback from a hook event.

        Args:
            hook_name: Name of the hook event.
            handler: Registered callback to remove.
        """
        if hook_name in self.handlers and handler in self.handlers[hook_name]:
            self.handlers[hook_name].remove(handler)

    def execute(self, hook_name: str, *args: Any, **kwargs: Any) -> None:
        """Safely execute all registered handlers for a given hook event.

        Args:
            hook_name: Name of the hook event to execute.
            *args: Positional arguments to pass to handlers.
            **kwargs: Keyword arguments to pass to handlers.
        """
        handlers = self.handlers.get(hook_name, [])
        for handler in handlers:
            try:
                handler(*args, **kwargs)
            except Exception as err:
                logger.error(f"Error executing hook handler '{hook_name}': {err}", exc_info=True)

    def pre_pipeline(self, context: Dict[str, Any]) -> None:
        """Trigger the pre_pipeline lifecycle hook with context.

        Args:
            context: Dictionary of pipeline run configuration parameters.
        """
        self.execute("pre_pipeline", context)

    def post_pipeline(self, context: Dict[str, Any]) -> None:
        """Trigger the post_pipeline lifecycle hook with execution result context.

        Args:
            context: Dictionary of pipeline completion results.
        """
        self.execute("post_pipeline", context)

    def trigger_on_log(self, message: str) -> None:
        """Trigger on_log hooks.

        Args:
            message: Log message string.
        """
        self.execute("on_log", message)

    def trigger_on_progress(self, current: int, total: int, step: str = "Processing...") -> None:
        """Trigger on_progress hooks.

        Args:
            current: Current chapter index.
            total: Total chapters count.
            step: Step description string.
        """
        self.execute("on_progress", current, total, step)

    def trigger_on_phase(self, phase: str, status: str) -> None:
        """Trigger on_phase hooks.

        Args:
            phase: Pipeline phase name.
            status: Phase status string.
        """
        self.execute("on_phase", phase, status)


_default_hook_manager = HookManager()


def get_hook_manager() -> HookManager:
    """Retrieve default global HookManager instance.

    Returns:
        HookManager: Global default HookManager singleton instance.
    """
    return _default_hook_manager
